# Site settings
title:          europfのノート
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://europf.github.io"

# Author
author:
  name:         europf

# Build settings
markdown:       kramdown
include:
  - _pages

kramdown:
  # 数式はKaTeXでレンダリングする
  math_engine: katex
  # 数式で'が別文字に変換するのを防ぐための設定
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale